### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by the4ndy** [madstanners/conf#1]
the link in the readme to your bootstrap file (http://jakestanley.net/bootstrap.sh) is giving a 404

**Comment by jakestanley** [comment]
All the bootstrap file did was apt-get install git and clone the repo. You can just do that manually.

**Comment by the4ndy** [comment]
I figured that our eventually. Sorry for being dumb, but then i got stuck as there was no install-all.sh script anymore. I tried manually running each script in the order they were in the "overhaul" fork script and then ran the remaining scripts (in arbitrary order). This was all done to a fresh Ubuntu 14.04 Virtual Box VM (the only thing that had been done was apt-get update and I installed the extras CD). I think I am missing something, cause I cannot get it to look like it did in your screenshot on Reddit. Any help would be greatly appreciated. Thanks

**Comment by jakestanley** [comment]
I sort of know the order in which I run the scripts, and I've been meaning to write a better single script for a while, I just haven't had the time. All my web dev stuff that wouldn't be needed for a general installation is in there, so that can be ignored. The scripts will require some tweaking as in places they may reference the absolute path of my home directory. 

Anyway, the best advice I can give is that I didn't start with any scripts or anything, I just did my research and found the programs that did what I wanted, and just picked up a few things from the dot files of other people I liked the look of.

The configure.sh and dotfiles.sh scripts are the most important, but mainly because they set the keyboard differently depending on whether I'm using a standard or Mac keyboard.

Thanks for taking an interest in my repo.

**Comment by jakestanley** [comment]
Attach a screenshot and I'll have a look
